
---
apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
spec:
  containers:
    - name: redis
      image: redis
      env: #Вказується звідки саме брати значення конкретної змінної
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret1
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret1
              key: password
  restartPolicy: Never
