---
apiVersion: batch/v1
kind: Job
metadata:
  name: reboot-server
spec:
  template:
    spec:
      containers:
      - name: reboot-server
        image: busybox
        command: ["/bin/sh", "-c", "reboot"]
      restartPolicy: OnFailure
  backoffLimit: 4
