apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - image: gcr.io/k8s-k3s-386915/demo:v1.0.0
      name: app
 
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
 
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        periodSeconds: 2
        initialDelaySeconds: 0
        failureThreshold: 3
        successThreshold: 1
      
      ports:
        - containerPort: 8080
          name: http
 
      volumeMounts:
      - mountPath: "/data"
        name: "data"     
    
  volumes:
    - name: "data"
      hostPath:
        path: "/var/lib/app"