---
apiVersion: v1
kind: Pod
metadata:
  name: app-resource
spec:
  containers:
    - image: gcr.io/k8s-k3s-386915/demo:v1.0.0
      name: app
      livenessProbe:
        httpGet:
          path: /ready
          port: 8000
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /ready
          port: 8000
        periodSeconds: 2
        initialDelaySeconds: 0
        failureThreshold: 3
        successThreshold: 1
      ports:
        - containerPort: 8000
          name: http
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 256Mi
