---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: demo
spec:
  containers:
    - name: app
      image: gcr.io/k8s-k3s-386915/demo:v1.0.0
      ports:
        - containerPort: 8000
          name: http
      livenessProbe:
        httpGet:
          path: /ready
          port: 8000
        initialDelaySeconds: 0
        periodSeconds: 2
        failureThreshold: 3
        successThreshold: 1
      readinessProbe:
        httpGet:
          path: /ready
          port: 8000
        initialDelaySeconds: 0
        periodSeconds: 2
        failureThreshold: 3
        successThreshold: 1
