---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels: 
    app: demo
    run: demo
spec:
  containers:
    - image: gcr.io/k8s-k3s-386915/demo:v1.0.0
      name: app
      ports:
        - containerPort: 8000
          name: http