---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: demo
    run: demo
spec:
  containers:
    - name: app
      image: gcr.io/k8s-k3s-386915/demo:v1.0.0
      ports:
        - name: http
          containerPort: 8000
