---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-live-check
spec:
  containers:
  - name: nginx-live-check
    image: nginx
    args: ["/bin/sh", "-c", "while true; do curl -I http://localhost; sleep 60; done"]
  restartPolicy: Always
